<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Tresorerie.Core">
      <HintPath>..\libs\Tresorerie.Core.dll</HintPath>
    </Reference>
    <Reference Include="Tresorerie.Dapper">
      <HintPath>..\libs\Tresorerie.Dapper.dll</HintPath>
    </Reference>
    <Reference Include="Ninject">
      <HintPath>..\libs\Ninject.dll</HintPath>
    </Reference>
    <Reference Include="Dapper">
      <HintPath>..\libs\Dapper.dll</HintPath>
    </Reference>
    <Reference Include="Tresorerie.ApplicationServices">
      <HintPath>..\libs\Tresorerie\Tresorerie.ApplicationServices.dll</HintPath>
    </Reference>
    <Reference Include="Tresorerie.Erp.ICore">
      <HintPath>..\libs\Tresorerie\Tresorerie.Erp.ICore.dll</HintPath>
    </Reference>
    <Reference Include="Tresorerie.IConfiguration">
      <HintPath>..\libs\Tresorerie\Tresorerie.IConfiguration.dll</HintPath>
    </Reference>
    <Reference Include="Tresorerie.Infrastructure">
      <HintPath>..\libs\Tresorerie\Tresorerie.Infrastructure.dll</HintPath>
    </Reference>
    <Reference Include="ApLicence.Core">
      <HintPath>..\libs\Tresorerie\ApLicence.Core.dll</HintPath>
    </Reference>
    <Reference Include="Tresorerie.Authorization.Core">
      <HintPath>..\libs\Tresorerie\Tresorerie.Authorization.Core.dll</HintPath>
    </Reference>
    <Reference Include="Tresorerie.UICommun">
      <HintPath>..\libs\Tresorerie\Tresorerie.UICommun.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GRC.Domain\GRC.Domain.csproj" />
    <ProjectReference Include="..\GRC.Application\GRC.Application.csproj" />
  </ItemGroup>

</Project>
